//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 05/04/2012 15:40:40
namespace HelloWorld.Model
{
    
    /// <summary>
    /// There are no comments for CotacoesBDEntities in the schema.
    /// </summary>
    public partial class CotacoesBDEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CotacoesBDEntities object using the connection string found in the 'CotacoesBDEntities' section of the application configuration file.
        /// </summary>
        public CotacoesBDEntities() : 
                base("name=CotacoesBDEntities", "CotacoesBDEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CotacoesBDEntities object.
        /// </summary>
        public CotacoesBDEntities(string connectionString) : 
                base(connectionString, "CotacoesBDEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CotacoesBDEntities object.
        /// </summary>
        public CotacoesBDEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CotacoesBDEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Cotacoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Cotacao> Cotacoes
        {
            get
            {
                if ((this._Cotacoes == null))
                {
                    this._Cotacoes = base.CreateQuery<Cotacao>("[Cotacoes]");
                }
                return this._Cotacoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Cotacao> _Cotacoes;
        /// <summary>
        /// There are no comments for Cotacoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCotacoes(Cotacao cotacao)
        {
            base.AddObject("Cotacoes", cotacao);
        }
    }
    /// <summary>
    /// There are no comments for CotacoesBDModel.Cotacao in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CotacoesBDModel", Name="Cotacao")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cotacao : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Cotacao object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="valor">Initial value of Valor.</param>
        /// <param name="data">Initial value of Data.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Cotacao CreateCotacao(int id, float valor, global::System.DateTime data)
        {
            Cotacao cotacao = new Cotacao();
            cotacao.Id = id;
            cotacao.Valor = valor;
            cotacao.Data = data;
            return cotacao;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property Codigo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this.OnCodigoChanging(value);
                this.ReportPropertyChanging("Codigo");
                this._Codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Codigo");
                this.OnCodigoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Codigo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoChanged();
        /// <summary>
        /// There are no comments for property Valor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public float Valor
        {
            get
            {
                return this._Valor;
            }
            set
            {
                this.OnValorChanging(value);
                this.ReportPropertyChanging("Valor");
                this._Valor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Valor");
                this.OnValorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private float _Valor;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnValorChanging(float value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnValorChanged();
        /// <summary>
        /// There are no comments for property Data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _Data;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDataChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDataChanged();
    }
}
