//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseUtils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataBaseUtils.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.000.
        /// </summary>
        internal static string ValorMaximoDOLAR {
            get {
                return ResourceManager.GetString("ValorMaximoDOLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.000.
        /// </summary>
        internal static string ValorMaximoETER3 {
            get {
                return ResourceManager.GetString("ValorMaximoETER3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.000.
        /// </summary>
        internal static string ValorMaximoGOLL4 {
            get {
                return ResourceManager.GetString("ValorMaximoGOLL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 350.000.
        /// </summary>
        internal static string ValorMaximoNATU3 {
            get {
                return ResourceManager.GetString("ValorMaximoNATU3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 207.45514325974636.
        /// </summary>
        internal static string ValorMaximoPETR4 {
            get {
                return ResourceManager.GetString("ValorMaximoPETR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 350.000.
        /// </summary>
        internal static string ValorMaximoVALE5 {
            get {
                return ResourceManager.GetString("ValorMaximoVALE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.000.
        /// </summary>
        internal static string ValorMinimoDOLAR {
            get {
                return ResourceManager.GetString("ValorMinimoDOLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.000.
        /// </summary>
        internal static string ValorMinimoETER3 {
            get {
                return ResourceManager.GetString("ValorMinimoETER3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.000.
        /// </summary>
        internal static string ValorMinimoGOLL4 {
            get {
                return ResourceManager.GetString("ValorMinimoGOLL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.000.
        /// </summary>
        internal static string ValorMinimoNATU3 {
            get {
                return ResourceManager.GetString("ValorMinimoNATU3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.034758102395489.
        /// </summary>
        internal static string ValorMinimoPETR4 {
            get {
                return ResourceManager.GetString("ValorMinimoPETR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.000.
        /// </summary>
        internal static string ValorMinimoVALE5 {
            get {
                return ResourceManager.GetString("ValorMinimoVALE5", resourceCulture);
            }
        }
    }
}
